<?php

return [
    'student' => [],
    'teacher' => [],
    'owner' => [
        "managment_students",
        "managment_media",
        "managment_majors",
        "managment_subject",
        'managment_roles',
        'managment_teachers',
        'managment_staff',
        'managment_lectures',
        'managment_academic_years',
        'managment_virtual_classroom',
        'managment_site_messages',
        'managment_settings',
        'managment_latestnews',
        "managment_honoraryboard",
        'managment_certificate',
        'managment_tests',
        'managment_groups',
        'managment_views',
        'managment_students_notes',
        "managment_analytics",
        "managment_schools",
        "managment_students_news",
        "managment_chats",
        "managment_notes",
        "managment_reports",
        "managment_courses",
        "managment_whyuse",
        "managment_services",
        "managment_student_teacher_notes",
        "managment_conference",
        "managment_doctconference",
    ]
];
